name: TheOS CI

on:
  push:
    #tags:
    #  - 'v*'

    #branches: [ master ]
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      debug_enabled:
        required: false
        default: ''

jobs:
  build:
    runs-on: macos-latest

    steps:
      ################################################
      ### Pre-init
      ################################################
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive  
      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote

      ################################################
      ### Setup Theos environment
      ################################################
      - name: Theos Setup (Check Cache)
        id: verify-cache
        run: |
          echo "::set-output name=heads::`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1`"

      - name: Theos Setup (Use Cache)
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ steps.verify-cache.outputs.heads }}

      - name: Theos Setup (Setup)
        uses: NyaMisty/theos-action@master
        with: 
          theos-sdks: https://github.com/theos/sdks
    
      - name: Setup libSandy
        run: |
          set -x

          if ! [ -d $THEOS/include/xpc ]; then
            git clone https://github.com/realthunder/mac-headers /tmp/mac-headers
            mv /tmp/mac-headers/usr/include/xpc $THEOS/include
          fi

          if ! [ -f $THEOS/include/libSandy.h ]; then
            git clone https://github.com/opa334/libSandy /tmp/libSandy
            cd /tmp/libSandy
            sed -i '' 's|export PREFIX=|#export PREFIX=|g' release_build.sh
            bash -x release_build.sh
            bash -x install_to_theos.sh
          fi
      
      - name: Prepare building
        run: |
          ln -s layout/Library/MobileSubstrate/DynamicLibraries/KbsyncTweak.plist
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Build Debug package
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          rm -f packages/*
          make package _THEOS_DARWIN_CAN_USE_MODULES=0 FINALPACKAGE=1
      
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: kbsynctool
          path: ${{ github.workspace }}/packages/*.deb

      - name: Get tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: tag
        uses: dawidd6/action-get-tag@v1
      
      - name: Build Release package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          rm -f packages/*
          TAGNAME=${{ steps.tag.outputs.tag }}
          make package _THEOS_DARWIN_CAN_USE_MODULES=0 FINALPACKAGE=1 PACKAGE_VERSION=${TAGNAME#v}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ${{ github.workspace }}/packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
